apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sc-routes.fullname" . }}
  labels:
    {{- include "sc-routes.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      deploymentconfig: {{ include "sc-routes.fullname" . }}
