{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "sc-routes.fullname" . }}
  labels:
    {{- include "sc-routes.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "sc-routes.fullname" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}
