apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: infinispan
spec:
  channel: 2.0.x
  installPlanApproval: Automatic
  name: infinispan
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: infinispan-operator.v2.0.1

